// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// Answer:  4613732
#include <stdio.h>

int fibonacci(int n)
{
    if (n < 2)
        return 1;
    return fibonacci(n - 1) + fibonacci(n - 2);
}

int main(int argc, char const *argv[])
{
    int i = 1;
    int limit = 4000000;
    int intermediate = 0;
    int answer = 0;
    int fibonacciValue = 0;
    while (fibonacciValue < limit)
    {
        fibonacciValue = fibonacci(i);
        if (fibonacciValue % 2 == 0)
        {
            answer += fibonacciValue;
        }
        i++;
    }
    printf("%d", answer);
    return 0;
}
